server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/librarymanagement?serverTimezone=GMT%2b8  #????
    username: root           #?????
    password: root           #?????


#mybatis??,??resource?mapper??????xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml
